package com.muslimedu.attendance.security

import android.content.Context
import com.google.crypto.tink.Aead
import com.google.crypto.tink.aead.AeadConfig
import com.google.crypto.tink.aead.AesGcmKeyManager
import com.google.crypto.tink.integration.android.AndroidKeysetManager
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * AES-256-GCM encryption for face templates (and anything else sensitive
 * that isn't the auth token, which [TokenManager] already handles via
 * EncryptedSharedPreferences). The data-encryption key is generated by Tink
 * and stored wrapped by an Android Keystore-held key (the `android-keystore://`
 * URI below), so the key material never exists outside the Keystore in
 * plaintext - satisfies the spec's "Android Keystore + Tink" requirement.
 */
@Singleton
class EncryptionHelper @Inject constructor(
    @ApplicationContext context: Context,
) {
    private val aead: Aead

    init {
        AeadConfig.register()
        val keysetManager = AndroidKeysetManager.Builder()
            .withSharedPref(context, KEYSET_NAME, PREF_FILE_NAME)
            .withKeyTemplate(AesGcmKeyManager.aes256GcmTemplate())
            .withMasterKeyUri(MASTER_KEY_URI)
            .build()
        aead = keysetManager.keysetHandle.getPrimitive(Aead::class.java)
    }

    fun encrypt(plaintext: ByteArray): ByteArray = aead.encrypt(plaintext, null)

    fun decrypt(ciphertext: ByteArray): ByteArray = aead.decrypt(ciphertext, null)

    companion object {
        private const val KEYSET_NAME = "face_template_keyset"
        private const val PREF_FILE_NAME = "face_template_keyset_prefs"
        private const val MASTER_KEY_URI = "android-keystore://face_template_master_key"
    }
}
